// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use the actual environment variables that we have configured
const SUPABASE_URL = "https://ylwcjuaeypeazdqypqst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsd2NqdWFleXBlYXpkcXlwcXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1ODE5MDEsImV4cCI6MjA1MzE1NzkwMX0.EY5qx5_cY--xWJFp7YW2KhwuWxJPd4bQRPwEU56b3Xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Supabase configuration missing. Please check environment variables.');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);